import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components/Header'
import { PrincipalSection } from '@/components/Sections/Initial'
import { BenefitsSection } from '@/components/Sections/benefits'
import { AboutSection } from '@/components/Sections/about'
import { OurServicesSection } from '@/components/Sections/ourServices'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>LG - Web Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <PrincipalSection />
          <BenefitsSection />
          <AboutSection />
          <OurServicesSection />
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {}
  }
}


